-- Mock transactional data for Q1-Q2 2026.
-- This script derives Reservation / Payment / Refund / PriceChangeLog
-- from the current Hotel + Room inventory.
-- FinancialLedger is generated by existing triggers when available,
-- and backfilled safely for any missing rows.

START TRANSACTION;

DELETE FROM FinancialLedger
WHERE ReferenceId LIKE 'PMT26%'
   OR ReferenceId LIKE 'RFD26%';

DELETE FROM Refund
WHERE RefundId LIKE 'RFD26%';

DELETE FROM Payment
WHERE PaymentId LIKE 'PMT26%';

DELETE FROM Reservation
WHERE ReservationId LIKE 'RSV26%';

DELETE FROM PriceChangeLog
WHERE LogId LIKE 'PCL26%';

DROP TEMPORARY TABLE IF EXISTS tmp_room_pool;
CREATE TEMPORARY TABLE tmp_room_pool (
    rn INT NOT NULL PRIMARY KEY,
    RoomId VARCHAR(10) NOT NULL,
    HotelId VARCHAR(24) NOT NULL,
    RoomType VARCHAR(100),
    BasePrice DECIMAL(18,2) NOT NULL,
    EffectivePrice DECIMAL(18,2) NOT NULL
);

INSERT INTO tmp_room_pool (
    rn,
    RoomId,
    HotelId,
    RoomType,
    BasePrice,
    EffectivePrice
)
SELECT
    ROW_NUMBER() OVER (ORDER BY r.HotelId, r.RoomId) AS rn,
    r.RoomId,
    r.HotelId,
    r.RoomType,
    r.BasePrice,
    COALESCE(NULLIF(r.CurrentPrice, 0), r.BasePrice) AS EffectivePrice
FROM Room r
INNER JOIN Hotel h ON h.HotelId = r.HotelId
WHERE COALESCE(r.Status, 1) = 1
  AND COALESCE(h.Status, 1) = 1;

SET @room_count := (SELECT COUNT(*) FROM tmp_room_pool);

DROP TEMPORARY TABLE IF EXISTS tmp_booking_scenarios;
CREATE TEMPORARY TABLE tmp_booking_scenarios (
    ScenarioNo INT PRIMARY KEY,
    UserId VARCHAR(10) NOT NULL,
    ReservationStatus VARCHAR(20) NOT NULL,
    CheckInAt DATETIME NOT NULL,
    CheckOutAt DATETIME NOT NULL,
    Payment1Type VARCHAR(50) NOT NULL,
    Payment1Ratio DECIMAL(5,2) NOT NULL,
    Payment1Date DATETIME NOT NULL,
    Payment2Type VARCHAR(50) NULL,
    Payment2Ratio DECIMAL(5,2) NULL,
    Payment2Date DATETIME NULL,
    RefundRatio DECIMAL(5,2) NULL,
    PenaltyRatio DECIMAL(5,2) NULL,
    RefundDate DATETIME NULL
);

INSERT INTO tmp_booking_scenarios (
    ScenarioNo,
    UserId,
    ReservationStatus,
    CheckInAt,
    CheckOutAt,
    Payment1Type,
    Payment1Ratio,
    Payment1Date,
    Payment2Type,
    Payment2Ratio,
    Payment2Date,
    RefundRatio,
    PenaltyRatio,
    RefundDate
) VALUES
    (1,  'USR2000001', 'Completed', '2026-01-08 14:00:00', '2026-01-10 12:00:00', 'FullPayment', 1.00, '2026-01-03 09:15:00', NULL,          NULL, NULL,                  NULL, NULL, NULL),
    (2,  'USR2000002', 'Completed', '2026-02-14 14:00:00', '2026-02-17 12:00:00', 'Deposit',     0.30, '2026-01-28 10:30:00', 'FinalPayment', 0.70, '2026-02-14 08:45:00', NULL, NULL, NULL),
    (3,  'USR2000003', 'Cancelled', '2026-03-22 14:00:00', '2026-03-25 12:00:00', 'Deposit',     0.30, '2026-02-05 11:20:00', NULL,          NULL, NULL,                  0.30, 0.00, '2026-02-18 16:10:00'),
    (4,  'USR2000004', 'Cancelled', '2026-04-18 14:00:00', '2026-04-21 12:00:00', 'FullPayment', 1.00, '2026-03-10 14:00:00', NULL,          NULL, NULL,                  0.70, 0.30, '2026-04-10 09:40:00'),
    (5,  'USR2000005', 'Completed', '2026-04-12 14:00:00', '2026-04-15 12:00:00', 'FullPayment', 1.00, '2026-04-05 13:30:00', NULL,          NULL, NULL,                  NULL, NULL, NULL),
    (6,  'USR2000006', 'Completed', '2026-05-10 14:00:00', '2026-05-13 12:00:00', 'Deposit',     0.30, '2026-04-22 15:45:00', 'FinalPayment', 0.70, '2026-05-10 09:05:00', NULL, NULL, NULL),
    (7,  'USR2000007', 'CheckedIn', '2026-05-24 14:00:00', '2026-05-28 12:00:00', 'Deposit',     0.30, '2026-05-08 12:20:00', 'FinalPayment', 0.70, '2026-05-24 08:30:00', NULL, NULL, NULL),
    (8,  'USR2000008', 'Confirmed', '2026-06-20 14:00:00', '2026-06-23 12:00:00', 'Deposit',     0.30, '2026-06-01 10:00:00', NULL,          NULL, NULL,                  NULL, NULL, NULL),
    (9,  'USR2000009', 'Completed', '2026-06-16 14:00:00', '2026-06-20 12:00:00', 'FullPayment', 1.00, '2026-06-05 16:20:00', NULL,          NULL, NULL,                  NULL, NULL, NULL),
    (10, 'USR2000010', 'Cancelled', '2026-06-28 14:00:00', '2026-07-02 12:00:00', 'FullPayment', 1.00, '2026-04-18 11:55:00', NULL,          NULL, NULL,                  1.00, 0.00, '2026-05-02 14:25:00'),
    (11, 'USR2000011', 'Completed', '2026-04-02 14:00:00', '2026-04-05 12:00:00', 'Deposit',     0.30, '2026-03-28 09:10:00', 'FinalPayment', 0.70, '2026-04-02 08:20:00', NULL, NULL, NULL),
    (12, 'USR2000012', 'Confirmed', '2026-07-08 14:00:00', '2026-07-11 12:00:00', 'FullPayment', 1.00, '2026-06-18 11:40:00', NULL,          NULL, NULL,                  NULL, NULL, NULL);

DROP TEMPORARY TABLE IF EXISTS tmp_mock_reservations;
CREATE TEMPORARY TABLE tmp_mock_reservations (
    ScenarioNo INT NOT NULL PRIMARY KEY,
    ReservationId VARCHAR(10) NOT NULL,
    RoomId VARCHAR(10) NOT NULL,
    HotelId VARCHAR(24) NOT NULL,
    RoomType VARCHAR(100),
    BasePrice DECIMAL(18,2) NOT NULL,
    EffectivePrice DECIMAL(18,2) NOT NULL,
    UserId VARCHAR(10) NOT NULL,
    ReservationStatus VARCHAR(20) NOT NULL,
    CheckInAt DATETIME NOT NULL,
    CheckOutAt DATETIME NOT NULL,
    StayNights INT NOT NULL,
    TotalAmount DECIMAL(18,2) NOT NULL,
    Payment1Type VARCHAR(50) NOT NULL,
    Payment1Ratio DECIMAL(5,2) NOT NULL,
    Payment1Date DATETIME NOT NULL,
    Payment2Type VARCHAR(50) NULL,
    Payment2Ratio DECIMAL(5,2) NULL,
    Payment2Date DATETIME NULL,
    RefundRatio DECIMAL(5,2) NULL,
    PenaltyRatio DECIMAL(5,2) NULL,
    RefundDate DATETIME NULL
);

INSERT INTO tmp_mock_reservations (
    ScenarioNo,
    ReservationId,
    RoomId,
    HotelId,
    RoomType,
    BasePrice,
    EffectivePrice,
    UserId,
    ReservationStatus,
    CheckInAt,
    CheckOutAt,
    StayNights,
    TotalAmount,
    Payment1Type,
    Payment1Ratio,
    Payment1Date,
    Payment2Type,
    Payment2Ratio,
    Payment2Date,
    RefundRatio,
    PenaltyRatio,
    RefundDate
)
SELECT
    s.ScenarioNo,
    CONCAT('RSV', LPAD(2600000 + s.ScenarioNo, 7, '0')) AS ReservationId,
    rp.RoomId,
    rp.HotelId,
    rp.RoomType,
    rp.BasePrice,
    rp.EffectivePrice,
    s.UserId,
    s.ReservationStatus,
    s.CheckInAt,
    s.CheckOutAt,
    GREATEST(TIMESTAMPDIFF(DAY, s.CheckInAt, s.CheckOutAt), 1) AS StayNights,
    ROUND(GREATEST(TIMESTAMPDIFF(DAY, s.CheckInAt, s.CheckOutAt), 1) * rp.EffectivePrice, 2) AS TotalAmount,
    s.Payment1Type,
    s.Payment1Ratio,
    s.Payment1Date,
    s.Payment2Type,
    s.Payment2Ratio,
    s.Payment2Date,
    s.RefundRatio,
    s.PenaltyRatio,
    s.RefundDate
FROM tmp_booking_scenarios s
INNER JOIN tmp_room_pool rp
    ON rp.rn = CASE
        WHEN @room_count = 0 THEN -1
        ELSE 1 + MOD(s.ScenarioNo - 1, @room_count)
    END;

INSERT INTO Reservation (
    ReservationId,
    RoomId,
    UserId,
    CheckInDate,
    CheckOutDate,
    Status
)
SELECT
    ReservationId,
    RoomId,
    UserId,
    CheckInAt,
    CheckOutAt,
    ReservationStatus
FROM tmp_mock_reservations;

DROP TEMPORARY TABLE IF EXISTS tmp_mock_payments;
CREATE TEMPORARY TABLE tmp_mock_payments (
    PaymentId VARCHAR(10) NOT NULL PRIMARY KEY,
    ReservationId VARCHAR(10) NOT NULL,
    PaymentType VARCHAR(50) NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    PaymentDate DATETIME NOT NULL,
    Status VARCHAR(50) NOT NULL
);

INSERT INTO tmp_mock_payments (
    PaymentId,
    ReservationId,
    PaymentType,
    Amount,
    PaymentDate,
    Status
)
SELECT
    CONCAT('PMT', LPAD(2600000 + (ScenarioNo * 2) - 1, 7, '0')) AS PaymentId,
    ReservationId,
    Payment1Type AS PaymentType,
    ROUND(TotalAmount * Payment1Ratio, 2) AS Amount,
    Payment1Date AS PaymentDate,
    'Completed' AS Status
FROM tmp_mock_reservations
WHERE Payment1Type IS NOT NULL;

INSERT INTO tmp_mock_payments (
    PaymentId,
    ReservationId,
    PaymentType,
    Amount,
    PaymentDate,
    Status
)
SELECT
    CONCAT('PMT', LPAD(2600000 + (ScenarioNo * 2), 7, '0')) AS PaymentId,
    ReservationId,
    Payment2Type AS PaymentType,
    ROUND(TotalAmount * Payment2Ratio, 2) AS Amount,
    Payment2Date AS PaymentDate,
    'Completed' AS Status
FROM tmp_mock_reservations
WHERE Payment2Type IS NOT NULL;

INSERT INTO Payment (
    PaymentId,
    ReservationId,
    PaymentType,
    Amount,
    PaymentDate,
    Status
)
SELECT
    PaymentId,
    ReservationId,
    PaymentType,
    Amount,
    PaymentDate,
    Status
FROM tmp_mock_payments;

DROP TEMPORARY TABLE IF EXISTS tmp_mock_refunds;
CREATE TEMPORARY TABLE tmp_mock_refunds (
    RefundId VARCHAR(10) NOT NULL PRIMARY KEY,
    ReservationId VARCHAR(10) NOT NULL,
    RefundAmount DECIMAL(18,2) NOT NULL,
    PenaltyAmount DECIMAL(18,2) NOT NULL,
    ProcessedAt DATETIME NOT NULL
);

INSERT INTO tmp_mock_refunds (
    RefundId,
    ReservationId,
    RefundAmount,
    PenaltyAmount,
    ProcessedAt
)
SELECT
    CONCAT('RFD', LPAD(2600000 + ScenarioNo, 7, '0')) AS RefundId,
    ReservationId,
    ROUND(TotalAmount * COALESCE(RefundRatio, 0), 2) AS RefundAmount,
    ROUND(TotalAmount * COALESCE(PenaltyRatio, 0), 2) AS PenaltyAmount,
    RefundDate AS ProcessedAt
FROM tmp_mock_reservations
WHERE RefundDate IS NOT NULL;

INSERT INTO Refund (
    RefundId,
    ReservationId,
    RefundAmount,
    PenaltyAmount,
    ProcessedAt
)
SELECT
    RefundId,
    ReservationId,
    RefundAmount,
    PenaltyAmount,
    ProcessedAt
FROM tmp_mock_refunds;

INSERT INTO FinancialLedger (
    LedgerId,
    ReferenceId,
    EventType,
    DebitAmount,
    CreditAmount,
    Date
)
SELECT
    SUBSTRING(REPLACE(UUID(), '-', ''), 1, 10) AS LedgerId,
    p.PaymentId AS ReferenceId,
    CASE UPPER(TRIM(p.PaymentType))
        WHEN 'DEPOSIT' THEN 'Deposit'
        WHEN 'FINALPAYMENT' THEN 'FinalPayment'
        WHEN 'FULLPAYMENT' THEN 'FullPayment'
        ELSE 'FullPayment'
    END AS EventType,
    p.Amount AS DebitAmount,
    0 AS CreditAmount,
    p.PaymentDate AS Date
FROM tmp_mock_payments p
WHERE NOT EXISTS (
    SELECT 1
    FROM FinancialLedger fl
    WHERE fl.ReferenceId = p.PaymentId
      AND fl.EventType = CASE UPPER(TRIM(p.PaymentType))
          WHEN 'DEPOSIT' THEN 'Deposit'
          WHEN 'FINALPAYMENT' THEN 'FinalPayment'
          WHEN 'FULLPAYMENT' THEN 'FullPayment'
          ELSE 'FullPayment'
      END
);

INSERT INTO FinancialLedger (
    LedgerId,
    ReferenceId,
    EventType,
    DebitAmount,
    CreditAmount,
    Date
)
SELECT
    SUBSTRING(REPLACE(UUID(), '-', ''), 1, 10) AS LedgerId,
    r.RefundId AS ReferenceId,
    'RefundPayout' AS EventType,
    0 AS DebitAmount,
    r.RefundAmount AS CreditAmount,
    r.ProcessedAt AS Date
FROM tmp_mock_refunds r
WHERE r.RefundAmount > 0
  AND NOT EXISTS (
      SELECT 1
      FROM FinancialLedger fl
      WHERE fl.ReferenceId = r.RefundId
        AND fl.EventType = 'RefundPayout'
  );

INSERT INTO FinancialLedger (
    LedgerId,
    ReferenceId,
    EventType,
    DebitAmount,
    CreditAmount,
    Date
)
SELECT
    SUBSTRING(REPLACE(UUID(), '-', ''), 1, 10) AS LedgerId,
    r.RefundId AS ReferenceId,
    'PenaltyRevenue' AS EventType,
    r.PenaltyAmount AS DebitAmount,
    0 AS CreditAmount,
    r.ProcessedAt AS Date
FROM tmp_mock_refunds r
WHERE r.PenaltyAmount > 0
  AND NOT EXISTS (
      SELECT 1
      FROM FinancialLedger fl
      WHERE fl.ReferenceId = r.RefundId
        AND fl.EventType = 'PenaltyRevenue'
  );

DROP TEMPORARY TABLE IF EXISTS tmp_price_log_scenarios;
CREATE TEMPORARY TABLE tmp_price_log_scenarios (
    LogNo INT PRIMARY KEY,
    ChangedAt DATETIME NOT NULL,
    OldFactor DECIMAL(5,2) NOT NULL,
    NewFactor DECIMAL(5,2) NOT NULL
);

INSERT INTO tmp_price_log_scenarios (LogNo, ChangedAt, OldFactor, NewFactor) VALUES
    (1, '2026-01-12 09:00:00', 0.92, 1.08),
    (2, '2026-02-11 14:15:00', 1.00, 1.65),
    (3, '2026-03-09 10:30:00', 1.12, 0.76),
    (4, '2026-04-14 16:45:00', 0.88, 1.34),
    (5, '2026-05-06 08:20:00', 1.05, 1.58),
    (6, '2026-05-28 13:40:00', 0.95, 1.18),
    (7, '2026-06-10 11:05:00', 1.08, 0.82),
    (8, '2026-06-24 17:10:00', 0.90, 1.52);

INSERT INTO PriceChangeLog (
    LogId,
    RoomId,
    OldPrice,
    NewPrice,
    ChangedAt
)
SELECT
    CONCAT('PCL', LPAD(2600000 + pls.LogNo, 7, '0')) AS LogId,
    rp.RoomId,
    ROUND(rp.EffectivePrice * pls.OldFactor, 2) AS OldPrice,
    ROUND(rp.EffectivePrice * pls.NewFactor, 2) AS NewPrice,
    pls.ChangedAt
FROM tmp_price_log_scenarios pls
INNER JOIN tmp_room_pool rp
    ON rp.rn = CASE
        WHEN @room_count = 0 THEN -1
        ELSE 1 + MOD(pls.LogNo - 1, @room_count)
    END;

COMMIT;

SELECT 'Reservation' AS TableName, COUNT(*) AS InsertedRows
FROM Reservation
WHERE ReservationId LIKE 'RSV26%'

UNION ALL

SELECT 'Payment' AS TableName, COUNT(*) AS InsertedRows
FROM Payment
WHERE PaymentId LIKE 'PMT26%'

UNION ALL

SELECT 'Refund' AS TableName, COUNT(*) AS InsertedRows
FROM Refund
WHERE RefundId LIKE 'RFD26%'

UNION ALL

SELECT 'FinancialLedger' AS TableName, COUNT(*) AS InsertedRows
FROM FinancialLedger
WHERE ReferenceId LIKE 'PMT26%'
   OR ReferenceId LIKE 'RFD26%'

UNION ALL

SELECT 'PriceChangeLog' AS TableName, COUNT(*) AS InsertedRows
FROM PriceChangeLog
WHERE LogId LIKE 'PCL26%';
